initial version of the test command
zenoss/zendev pull request #286
Opened 2016-09-16 22:06 UTC by tgjonestx

Requires changes in https://github.com/zenoss/product-assembly/pull/62

**Examples:**

Run all of the tests in the current devimg, including any zenpacks (in this case, core zenpacks)
```
zendev devimg --clean -p core
zendev test
```

Run just the prodbin tests
```
zendev devimg --clean
zendev test -- --no-zenpacks
```

Run tests for a single ZenPack
```
zendev devimg --clean -p core
zendev test -- --type=unit --name ZenPacks.zenoss.LinuxMonitor
```

2016-09-16 22:31 UTC, jplouis commented on zendev/cmd/test.py
> +    mounts = {
Any way we can share the list of mounts into devimg https://github.com/zenoss/zendev/blob/zendev2/zendev/cmd/serviced.py#L370

2016-09-16 22:32 UTC, jplouis requested changes

2016-09-16 22:36 UTC, tgjonestx commented on zendev/cmd/test.py
> +    mounts = {
Let me see

2016-09-19 16:17 UTC, jplouis approved these changes

2016-09-19 16:17 UTC, merged